// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

package com.helloworld.modelproto;

public interface ContactIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ContactId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
