// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

package com.helloworld.modelproto;

public final class Contact {
  private Contact() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContactProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ContactProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContactId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ContactId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontact.proto\"P\n\014ContactProto\022\n\n\002id\030\001 " +
      "\001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001" +
      "(\t\022\r\n\005phone\030\004 \001(\t\"7\n\010Response\022\n\n\002id\030\003 \001(" +
      "\005\022\017\n\007message\030\001 \001(\t\022\016\n\006STATUS\030\002 \001(\005\"\027\n\tCo" +
      "ntactId\022\n\n\002id\030\001 \001(\005B\035\n\031com.helloworld.mo" +
      "delprotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ContactProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ContactProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ContactProto_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Phone", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Id", "Message", "STATUS", });
    internal_static_ContactId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ContactId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ContactId_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
