// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

package com.helloworld.modelproto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 3;</code>
   */
  int getId();

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 STATUS = 2;</code>
   */
  int getSTATUS();
}
